- name: Setup inventory&groups
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - misc
  tasks:
    - name: Get the first user ID (will be the real user)
      shell: grep ^UID_MIN /etc/login.defs | cut -f2 -d' '
      register: uid
    - name: get user's name
      getent:
        database: passwd
        key: "{{ uid.stdout }}"
        split: ':'
        # {{ lookup('dict', getent_passwd).key }} is the user with ID 1000


    - name: Add host to username group and set fact with username
      add_host:
        name: '{{ ansible_hostname }}'
        groups: '{{ lookup('dict', getent_passwd).key }}'
        primary_user: '{{ lookup('dict', getent_passwd).key }}'
        ansible_connection: local
        # Now can use {{ hostvars[ansible_hostname][primary_user] }}
        # Being in the user's name group means they can use group_vars/username
    - name: Add to developers group
      add_host:
        name: '{{ ansible_hostname }}'
        groups: developers
        when: in(lookup('dict', getent_passwd).key , developers )
- name: Install Generic stuff for everyone
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root

# We shouldn't need to do this, it is idempotent.
# However, skipping the whole role causes fewer "skipping" log messages
  tasks:
    - service:
        name: bd
      register: bd_service
    - name: BitDefender
      include_role:
        name: bitdefender
      when: bd_service.status.LoadState != 'loaded'

    - stat:
        path: /run/docker.sock
      register: docker_path
    - name: Docker
      include_role:
        name: docker
      when: not docker_path.stat.exists

    - stat:
        path: /usr/lib/virtualbox/
      register: vbox_path
    - name: VirtualBox
      include_role:
        name: virtualbox
      when: not vbox_path.stat.exists



- name: Install stuff for developers
  hosts: developers
  roles:
    - chrome
    - jdk
    - intellij
# Actually listed jdk as a dependency for intellij (in meta), so shouldn't need to name it here.
# If anyone starts adding different JDKs, that might need "tidying"

- name: Install stuff for max
  hosts: max-*
  become: yes
  become_method: sudo
  become_user: root
  connection: local
  roles:
    - sshd
