- name: Install Generic stuff for everyone
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - stat:
        path: /opt/BitDefender
      register: bd_path
    - name: BitDefender
      include_role:
        name: bitdefender
      when: bd_path.stat.exists == true and bd_path.stat.isdir == true

    - stat:
        path: /run/docker
      register: docker_path
    - name: Docker
      include_role:
        name: docker
      when: docker_path.stat.exists
# We shouldn't need to do this, it is idempotent.
# However, skipping the whole role causes fewer "skipping" log messages
- name: Install stuff for max
  hosts: max-*
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - sshd
