- name: Install Generic stuff for everyone
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root

# We shouldn't need to do this, it is idempotent.
# However, skipping the whole role causes fewer "skipping" log messages
  tasks:
    - service:
        name: bd
      register: bd_service
    - name: BitDefender
      include_role:
        name: bitdefender
      when: bd_service.status.LoadState != 'loaded'

    - stat:
        path: /run/docker
      register: docker_path
    - name: Docker
      include_role:
        name: docker
      when: not docker_path.stat.exists

    - stat:
        path: /usr/lib/virtualbox/
      register: vbox_path
    - name: VirtualBox
      include_role:
        name: virtualbox
      when: not vbox_path.stat.exists


- name: Install stuff for developers
  hosts: developers
  roles:
    - chrome
    - jdk
    - intellij
# Actually listed jdk as a dependency for intellij (in meta), so shouldn't need to name it here.
# If anyone starts adding different JDKs, that might need "tidying"

- name: Install stuff for max
  hosts: max-*
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - sshd
