---
- name: Remove conflicting/old packages
  apt:
    name: docker-ce
    state: absent
- name: Remove conflicting/old packaßges
  apt:
    name: docker-ce-cli
    state: absent
- name: Remove conflicting/old packages
  apt:
    name: containerd.io
    state: absent

- name: Add the Apt signing key,
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Allow user to use Docker by putting their name in the group
  user:
    name: "{{ hostvars[ansible_hostname]['primary_user'] }}"
    groups: docker
    append: true
