---
# tasks file for docker
- name: Install docker
  package:
    name: docker.io
    state: present


- name: Allow user to use Docker by putting their name in the group
  user:
    name: "{{ hostvars[ansible_hostname][primary_user] }}"
    groups: docker
    append: true
