---
# tasks file for virtualbox


- apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib"
    state: present
  when: ansible_distribution_file_variety == "Debian"

- name: add key
  apt-key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    finger: B9F8 D658 297A F3EF C18D  5CDF A2F6 83C5 2980 AECF
  when: ansible_distribution_file_variety == "Debian"

- name: Install virtualbox
  apt:
    update_cache: true
    name: virtualbox-6.1
    state: present
  when: ansible_distribution_file_variety == "Debian"
    
