---
# tasks file for virtualbox

- name: add key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  when: ansible_distribution_file_variety == "Debian"

- apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib"
    state: present
  when: ansible_distribution_file_variety == "Debian"

- name: Install virtualbox
  apt:
    update_cache: true
    name: virtualbox-6.1
    state: present
  when: ansible_distribution_file_variety == "Debian"
