---
# tasks file for intellij

- name: Get role from galaxy
  command: ansible-galaxy gantsign.intellij

- name: Install the role
  include_role:
    name: gantsign.intellij
    private: false
    #In ansible 2.7+ this is public: true
