---
# tasks file for bitdefender
- name: create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: tempdir


- name: Download/extract
  uncompress:
    src: https://cloudgz-ecs.gravityzone.bitdefender.com/Packages/NIX/0/z-oEXO/Bitdefender_for_Linux.tar
    dest: "{{ tempdir.path }}"
    mode: "01777"
- name: Run the installer
  command: "{{ tempdir.path }}/installer"
    chdir: "{{ tempdir.path }}"
    creates: /opt/BitDefender
- name: Destroy evidence!
  file:
    state: absent
    path: "{{ tempdir.path }}"
